INSERT INTO desks (desk_id, name)
VALUES
    (gen_random_uuid(), 'ООП'),
    (gen_random_uuid(), 'SOLID'),
    (gen_random_uuid(), 'Java Core'),
    (gen_random_uuid(), 'Коллекции'),
    (gen_random_uuid(), 'Исключения'),
    (gen_random_uuid(), 'Дженерики'),
    (gen_random_uuid(), 'Функциональные интерфейсы'),
    (gen_random_uuid(), 'Stream API'),
    (gen_random_uuid(), 'Многопоточность'),
    (gen_random_uuid(), 'Базы данных'),
    (gen_random_uuid(), 'SQL'),
    (gen_random_uuid(), 'NoSQL'),
    (gen_random_uuid(), 'Миграции'),
    (gen_random_uuid(), 'ORM'),
    (gen_random_uuid(), 'Spring'),
    (gen_random_uuid(), 'Паттерны проектирования'),
    (gen_random_uuid(), 'WEB'),
    (gen_random_uuid(), 'Микросервисы'),
    (gen_random_uuid(), 'Брокеры сообщений'),
    (gen_random_uuid(), 'Тестирование'),
    (gen_random_uuid(), 'Деплой'),
    (gen_random_uuid(), 'Другое');